// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.2
// source: proto/apigatewayservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityName string `protobuf:"bytes,1,opt,name=cityName,proto3" json:"cityName,omitempty"`
}

func (x *UserCityRequest) Reset() {
	*x = UserCityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apigatewayservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCityRequest) ProtoMessage() {}

func (x *UserCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apigatewayservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCityRequest.ProtoReflect.Descriptor instead.
func (*UserCityRequest) Descriptor() ([]byte, []int) {
	return file_proto_apigatewayservice_proto_rawDescGZIP(), []int{0}
}

func (x *UserCityRequest) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

type UserWeatherReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weather string `protobuf:"bytes,1,opt,name=weather,proto3" json:"weather,omitempty"`
}

func (x *UserWeatherReply) Reset() {
	*x = UserWeatherReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_apigatewayservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserWeatherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserWeatherReply) ProtoMessage() {}

func (x *UserWeatherReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apigatewayservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserWeatherReply.ProtoReflect.Descriptor instead.
func (*UserWeatherReply) Descriptor() ([]byte, []int) {
	return file_proto_apigatewayservice_proto_rawDescGZIP(), []int{1}
}

func (x *UserWeatherReply) GetWeather() string {
	if x != nil {
		return x.Weather
	}
	return ""
}

var File_proto_apigatewayservice_proto protoreflect.FileDescriptor

var file_proto_apigatewayservice_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0x2d, 0x0a, 0x0f,
	0x55, 0x73, 0x65, 0x72, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x55,
	0x73, 0x65, 0x72, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x32, 0x5f, 0x0a, 0x11, 0x41, 0x70, 0x69,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x2e,
	0x61, 0x70, 0x69, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x5a, 0x69, 0x67, 0x61, 0x6e, 0x73, 0x68,
	0x69, 0x6e, 0x44, 0x65, 0x76, 0x2f, 0x74, 0x67, 0x2d, 0x62, 0x6f, 0x74, 0x2d, 0x77, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_apigatewayservice_proto_rawDescOnce sync.Once
	file_proto_apigatewayservice_proto_rawDescData = file_proto_apigatewayservice_proto_rawDesc
)

func file_proto_apigatewayservice_proto_rawDescGZIP() []byte {
	file_proto_apigatewayservice_proto_rawDescOnce.Do(func() {
		file_proto_apigatewayservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_apigatewayservice_proto_rawDescData)
	})
	return file_proto_apigatewayservice_proto_rawDescData
}

var file_proto_apigatewayservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_apigatewayservice_proto_goTypes = []interface{}{
	(*UserCityRequest)(nil),  // 0: api_gateway.UserCityRequest
	(*UserWeatherReply)(nil), // 1: api_gateway.UserWeatherReply
}
var file_proto_apigatewayservice_proto_depIdxs = []int32{
	0, // 0: api_gateway.ApiGatewayService.GetUserCity:input_type -> api_gateway.UserCityRequest
	1, // 1: api_gateway.ApiGatewayService.GetUserCity:output_type -> api_gateway.UserWeatherReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_apigatewayservice_proto_init() }
func file_proto_apigatewayservice_proto_init() {
	if File_proto_apigatewayservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_apigatewayservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_apigatewayservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserWeatherReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_apigatewayservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_apigatewayservice_proto_goTypes,
		DependencyIndexes: file_proto_apigatewayservice_proto_depIdxs,
		MessageInfos:      file_proto_apigatewayservice_proto_msgTypes,
	}.Build()
	File_proto_apigatewayservice_proto = out.File
	file_proto_apigatewayservice_proto_rawDesc = nil
	file_proto_apigatewayservice_proto_goTypes = nil
	file_proto_apigatewayservice_proto_depIdxs = nil
}
